### ISSUE TITLE
Implement CI

### ISSUE THREAD

**Issue by Ishamyyl** [Ishamyyl/drip-python#3]
- [x] 1. Branch structure
- [x] 0. Make repo public
- [x] 1. Research approach -- requirements: 
* free (not travis-ci anymore feelsbadman)
  * AppVeyor
  * CircleCI
* automatic versioning [ ]
* automatic badges ~~"status cards" (100% test, 100% coverage, etc, can't remember what they're called)~~
  * [x] coverage -> coveralls.io
  * [ ] tests/build -> custom 
- [x] 2. Convert to Pipenv 
- [x] 3. Implement
* Tests pass required for merge to dev branch
